# Generated by Django 3.1.7 on 2021-04-16 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=2)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('English_class', models.CharField(blank=True, max_length=2)),
                ('position', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeTable',
            fields=[
                ('college_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOpenTable',
            fields=[
                ('opencourse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('semaster', models.CharField(max_length=20)),
                ('course_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True)),
                ('opencourse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.courseopentable')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=4)),
                ('credit_hour', models.IntegerField(default=40)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseopentable',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.coursetable'),
        ),
        migrations.AddField(
            model_name='user',
            name='college_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myWeb.collegetable'),
        ),
    ]
