# Generated by Django 3.1.7 on 2021-04-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='college', to='myWeb.collegetable'),
        ),
    ]
