# Generated by Django 3.1.7 on 2021-05-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretable',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
