# Generated by Django 3.1.7 on 2021-04-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='teacher',
            new_name='user',
        ),
    ]
